//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaSy.Web.Resources.Areas.Identity.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Disable2fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Disable2fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaSy.Web.Resources.Areas.Identity.Pages.Account.Manage.Disable2fa", typeof(Disable2fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string ActionDisables2fa {
            get {
                return ResourceManager.GetString("ActionDisables2fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot disable 2FA for user with ID &apos;{0}&apos; as it&apos;s not currently enabled..
        /// </summary>
        public static string CannotDisable2fa {
            get {
                return ResourceManager.GetString("CannotDisable2fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Disable2FAButton {
            get {
                return ResourceManager.GetString("Disable2FAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should reset your authenticator keys..
        /// </summary>
        public static string Disable2faDesc {
            get {
                return ResourceManager.GetString("Disable2faDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        public static string Disable2faTitle {
            get {
                return ResourceManager.GetString("Disable2faTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator keys.
        /// </summary>
        public static string ResetAuthenticatorKeys {
            get {
                return ResourceManager.GetString("ResetAuthenticatorKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2fa has been disabled. You can reenable 2fa when you setup an authenticator app..
        /// </summary>
        public static string StatusMsg2faDisabled {
            get {
                return ResourceManager.GetString("StatusMsg2faDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user with ID &apos;{0}&apos;..
        /// </summary>
        public static string UnableToLoadUser {
            get {
                return ResourceManager.GetString("UnableToLoadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred disabling 2FA for user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Unexpected2faError {
            get {
                return ResourceManager.GetString("Unexpected2faError", resourceCulture);
            }
        }
    }
}
