//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaSy.Web.Resources.Areas.Identity.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TwoFactorAuthentication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwoFactorAuthentication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaSy.Web.Resources.Areas.Identity.Pages.Account.Manage.TwoFactorAuthentication", typeof(TwoFactorAuthentication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string AddAuthenticatorApp {
            get {
                return ResourceManager.GetString("AddAuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator app.
        /// </summary>
        public static string AuthenticatorApp {
            get {
                return ResourceManager.GetString("AuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Disable2FA {
            get {
                return ResourceManager.GetString("Disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string ForgetThisBrowser {
            get {
                return ResourceManager.GetString("ForgetThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string NoCodesLeft {
            get {
                return ResourceManager.GetString("NoCodesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        public static string OneCodeLeft {
            get {
                return ResourceManager.GetString("OneCodeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string ResetAuthenticatorApp {
            get {
                return ResourceManager.GetString("ResetAuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string ResetRecoveryCcodes {
            get {
                return ResourceManager.GetString("ResetRecoveryCcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup authenticator app.
        /// </summary>
        public static string SetupAuthenticatorApp {
            get {
                return ResourceManager.GetString("SetupAuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current browser has been forgotten. When you login again from this browser you will be prompted for your 2fa code..
        /// </summary>
        public static string StatusMessageBrowserForgotten {
            get {
                return ResourceManager.GetString("StatusMessageBrowserForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication (2FA).
        /// </summary>
        public static string Title2fa {
            get {
                return ResourceManager.GetString("Title2fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user with ID &apos;{0}&apos;..
        /// </summary>
        public static string UnableToLoadUser {
            get {
                return ResourceManager.GetString("UnableToLoadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can.
        /// </summary>
        public static string YouCan_1 {
            get {
                return ResourceManager.GetString("YouCan_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate a new set of recovery codes.
        /// </summary>
        public static string YouCan_2 {
            get {
                return ResourceManager.GetString("YouCan_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string YouCan_3 {
            get {
                return ResourceManager.GetString("YouCan_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} recovery codes left..
        /// </summary>
        public static string YouHaveXCodesLeft {
            get {
                return ResourceManager.GetString("YouHaveXCodesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must.
        /// </summary>
        public static string YouMust_1 {
            get {
                return ResourceManager.GetString("YouMust_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate a new set of recovery codes.
        /// </summary>
        public static string YouMust_2 {
            get {
                return ResourceManager.GetString("YouMust_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before you can log in with a recovery code..
        /// </summary>
        public static string YouMust_3 {
            get {
                return ResourceManager.GetString("YouMust_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should.
        /// </summary>
        public static string YouShould_1 {
            get {
                return ResourceManager.GetString("YouShould_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate a new set of recovery codes.
        /// </summary>
        public static string YouShould_2 {
            get {
                return ResourceManager.GetString("YouShould_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string YouShould_3 {
            get {
                return ResourceManager.GetString("YouShould_3", resourceCulture);
            }
        }
    }
}
